### ISSUE TITLE
Build Sign Up Component

### ISSUE THREAD

**Issue by ry4-n** [VividCiphers/vivid-ciphers-website#7]
http://vividciphers.com/register/

Please create a new angular component that represents the current register page.  You mean need to google "Angular 2 forms" to get an idea about how to gather data. 

- Generate a new component (ng generate component signup-page) 
- In the template, copy the current HTML into the template for the new component.
- Look into how validation works for angular 2 forms and apply it (also, HTML5 validation).
- The sign up button should be wired to an event handler in the component.  Nothing needs to happen right now, eventually this will call the Laravel API.

**Comment by gp22** [comment]
I just created a pull request for the initial version of this. Let me know what you think.

**Comment by ry4-n** [comment]
Merged the pull request.  Everything looks great! Thanks!
