### ISSUE TITLE
Build Forgot Password Component

### ISSUE THREAD

**Issue by ry4-n** [VividCiphers/vivid-ciphers-website#9]
Please create a new component that represents a forgot password page.  Currently there is no markup for this, so please use the Sign Up and Sign In pages as reference. 

- Build Markup
- Generate a new component (ng generate component forgot-password-page)
- Look into how validation works for angular 2 forms and apply it (also, HTML5 validation).
- Functionality can be similar to how Sign Up component is implemented with an empty object in the class.

**Comment by gp22** [comment]
I just created a pull request for the initial version. Similar to signup page.
Also, I'm not sure if I'm doing my branches correctly. I created a feature branch off of rework for the signup-page, and didn't merge it back into rework. Then I created another feature branch off of rework for the forgot-password-page and didn't merge that one either.
This created merge conflicts in the rework branch. Let me know how you would handle this.
PS: I'm studying reactive forms in Angular right now.

**Comment by ry4-n** [comment]
@gp22 Lets discuss branches next time we're both online.  

The forgot password page looks good minus one small change I made.  Thanks again for awesome work!

**Comment by gp22** [comment]
Great, yeah I'm struggling with branching. My local repo got out of sync and I couldn't figure out what was going on so I just deleted it and re-cloned from master. Not the best approach, I know!
I'd like to have a way of creating feature branches and keeping track of them separately from the rework branch in case they need to be changed.
I'm trying to duplicate something like this: http://nvie.com/posts/a-successful-git-branching-model/
